platform :ios, '9.0'
inhibit_all_warnings!
pod 'AFNetworking'
pod 'hpple'
pod 'MJRefresh'
pod 'MJExtension'
pod 'HMSegmentedControl'
pod 'SDWebImage'
pod 'UIActivityIndicator-for-SDWebImage'
pod 'SVProgressHUD'
pod 'NHBalancedFlowLayout'
pod 'YTKNetwork'
pod 'MWPhotoBrowser'
pod 'ReactiveCocoa', '~> 2.5'
